spring:
  application:
    name: candidate-position-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/candidate_position_management_system?createDatabaseIfNotExist=true
    username: root
    password: manager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

#http://localhost:8080/swagger-ui.html