spring:
  application:
    name: candidate-position-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/candidate_position_management_system?createDatabaseIfNotExist=true
    username: root
    password: manager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
